language: scala
sudo: required
dist: trusty

matrix:
  include:
    # Scala 2.11
    - jdk: oraclejdk8
      scala: 2.11.11
      env: COMMAND=ci-jvm COVERAGE=coverage
    - jdk: oraclejdk8
      scala: 2.11.11
      env: COMMAND=ci-js COVERAGE=
    # Scala 2.12
    - jdk: oraclejdk8
      scala: 2.12.2
      env: COMMAND=ci-jvm-all COVERAGE=
    - jdk: oraclejdk8
      scala: 2.12.2
      env: COMMAND=ci-js COVERAGE=

env:
  global:
    - TRAVIS_NODE_VERSION="6.10" # LTS

# http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - export SBT_PROFILE=$COVERAGE
  - travis_wait 30 sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COVERAGE $COMMAND

after_success:
  - |
    if [ "$COVERAGE" = "coverage" ]; then
      export SBT_PROFILE=$COVERAGE
      sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coverageReport
      bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
