language: scala
sudo: required
dist: trusty
group: edge

matrix:
  include:
    # Scala 2.11, JVM
    - jdk: oraclejdk8
      scala: 2.11.12
      env:
        - COMMAND=ci-jvm-mima
        - SCALAJS_VERSION=0.6.32
    # Scala 2.11, JavaScript
    - jdk: oraclejdk8
      scala: 2.11.12
      env:
        - COMMAND=ci-js
        - SCALAJS_VERSION=0.6.32
    # Scala 2.12, JVM
    - jdk: oraclejdk8
      scala: 2.12.10
      env:
        - COMMAND=ci-jvm
        - SCALAJS_VERSION=
    # Scala 2.12, JavaScript
    - jdk: oraclejdk8
      scala: 2.12.10
      env:
        - COMMAND=ci-js
        - SCALAJS_VERSION=1.0.0
    # Scala 2.13, JVM
    - jdk: oraclejdk8
      scala: 2.13.1
      env:
        - COMMAND=ci-jvm-all
        - SCALAJS_VERSION=
    # Scala 2.13, JVM, JDK 11
    - jdk: openjdk11
      scala: 2.13.1
      env:
        - COMMAND=ci-jvm
        - SCALAJS_VERSION=
    # Scala 2.13, JavaScript 0.6.32
    - jdk: oraclejdk8
      scala: 2.13.1
      env:
        - COMMAND=ci-js
        - SCALAJS_VERSION=0.6.32
    # Scala 2.13, JavaScript 1.0.0
    - jdk: oraclejdk8
      scala: 2.13.1
      env:
        - COMMAND=ci-js
        - SCALAJS_VERSION=1.0.0

env:
  global:
    - TRAVIS_NODE_VERSION="8.9" # LTS

# http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COMMAND

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
