name: build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ["v[0-9]+*"]

jobs:
  jvm-tests:
    name: JVM / scala ${{ matrix.scala }}, jdk ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        # WARN: build.sbt depends on this key path, as scalaVersion and
        # crossScalaVersions is determined from it
        scala: [ 2.11.12, 2.12.12, 2.13.3 ]

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ci-jvm
        run: |
          if [[ "$SCALA_VERSION"~="2.11" ]]; then
            export SCALAJS_VERSION="0.6.33"
          fi
          ./.github/scripts/build
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          PLATFORM: ${{ matrix.java }}
          SBT_COMMAND: ci-jvm

  js-tests:
    name: JS / scala ${{ matrix.scala }}, sjs ${{ matrix.scalajs }}, jdk ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # WARN: build.sbt depends on this key path, as scalaVersion and
        # crossScalaVersions is determined from it
        include:
          - { java: 8, scala: 2.11.12, scalajs: 0.6.33 }
          - { java: 8, scala: 2.12.12, scalajs: 0.6.33 }
          - { java: 8, scala: 2.12.12, scalajs: 1.1.1 }
          - { java: 8, scala: 2.13.3, scalajs: 0.6.33 }
          - { java: 8, scala: 2.13.3, scalajs: 1.1.1 }

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ci-js
        run: |
          ./.github/scripts/build
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          PLATFORM: ${{ matrix.java }}
          SBT_COMMAND: ci-js

  mima:
    name: Mima / scala ${{ matrix.scala }}, sjs ${{ matrix.scalajs }}, jdk ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { java: 8, scala: 2.11.12, scalajs: 0.6.33 }
          - { java: 8, scala: 2.12.12, scalajs: 1.1.1 }
          - { java: 8, scala: 2.13.3, scalajs: 1.1.1 }

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt mimaReportBinaryIssues
        run: |
          ./.github/scripts/build
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: mimaReportBinaryIssues

  unidoc:
    name: Unidoc / scala ${{ matrix.scala }}, sjs ${{ matrix.scalajs }}, jdk ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { java: 8, scala: 2.13.3, scalajs: 1.1.1 }

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt unidoc
        run: |
          ./.github/scripts/build
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: unidoc

  publish:
    name: Publish to Sonatype
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master')
    needs: [ jvm-tests, js-tests, mima, unidoc ]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        scalajs: ["", 0.6.33, 1.1.1]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-gpg@v2
      - uses: olafurpg/setup-scala@v2
        with:
          java-version: "adopt@1.8"

      - name: SCALAJS_VERSION=${{ matrix.scalajs }} sbt ci-release
        run: |
          echo "SCALAJS_VERSION=$SCALAJS_VERSION"
          sbt clean ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SCALAJS_VERSION: ${{ matrix.scalajs }}
