name: manual-publish

on: 
  workflow_dispatch:
    inputs:
      ref_to_publish:
        description: 'Ref (branch or tag)'     
        required: true
        default: 'refs/heads/series/3.x'
      stable_version:
        description: 'Stable version? (true=staging, false=snapshot)'
        required: true
        default: "true"

jobs:
  publish:
    name: Publish to Sonatype (Request)
    strategy:
      matrix:
        scalajs: ["", 0.6.33, 1.1.1]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.inputs.ref_to_publish }}

      - uses: olafurpg/setup-scala@v2
        with:
          java-version: "adopt@1.8"

      - name: Install GnuPG2
        run: |
          ./.github/scripts/setup-pgp
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: SCALAJS_VERSION=${{ matrix.scalajs }} sbt ci-release
        run: |
          echo "SCALAJS_VERSION=$SCALAJS_VERSION"
          git fetch --depth=100 origin +refs/tags/*:refs/tags/*
          if [ "$PUBLISH_STABLE_VERSION" = "true" ]; then
            sbt ci-release
          else
            sbt +clean +publishSigned
          fi
        env:
          PGP_KEY_HEX: ${{ secrets.PGP_KEY_HEX }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SCALAJS_VERSION: ${{ matrix.scalajs }}
          PUBLISH_STABLE_VERSION: ${{ github.event.inputs.stable_version }}
